STORES = {
    "chipotle": "Eating Out",
    "trader joes": "Groceries",
    "starbucks": "Eating Out",
    "fuel" : "Gas",
    "zehrs" : "Groceries",
    "a&w" : "Dining",
    "loblaw" : "Groceries",
    "farms" : "Groceries",
    "economical" : "Car Insurance",
    "tim hortons" : "Dining",
    "quesada" : "Dining",
    "sobeys" : "groceries",
    "skipthedishes" : "Dining",
    "poke" : "dining",
    "lcbo" : "Alcohol",
    "wal-mart" : "Groceries",
    "amazon" : "Misc",  
    "petro" : "Gas",
 }
